//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPClient.SenecaES {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeBase", Namespace="http://schemas.datacontract.org/2004/07/AssociationsOther.Controllers")]
    [System.SerializableAttribute()]
    public partial class EmployeeBase : SOAPClient.SenecaES.EmployeeAdd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeAdd", Namespace="http://schemas.datacontract.org/2004/07/AssociationsOther.Controllers")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOAPClient.SenecaES.EmployeeBase))]
    public partial class EmployeeAdd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SenecaES.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/HelloWorld", ReplyAction="http://tempuri.org/IEmployeeService/HelloWorldResponse")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/HelloWorld", ReplyAction="http://tempuri.org/IEmployeeService/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AllEmployees", ReplyAction="http://tempuri.org/IEmployeeService/AllEmployeesResponse")]
        SOAPClient.SenecaES.EmployeeBase[] AllEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AllEmployees", ReplyAction="http://tempuri.org/IEmployeeService/AllEmployeesResponse")]
        System.Threading.Tasks.Task<SOAPClient.SenecaES.EmployeeBase[]> AllEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/EmployeeById", ReplyAction="http://tempuri.org/IEmployeeService/EmployeeByIdResponse")]
        SOAPClient.SenecaES.EmployeeBase EmployeeById(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/EmployeeById", ReplyAction="http://tempuri.org/IEmployeeService/EmployeeByIdResponse")]
        System.Threading.Tasks.Task<SOAPClient.SenecaES.EmployeeBase> EmployeeByIdAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AddEmployee", ReplyAction="http://tempuri.org/IEmployeeService/AddEmployeeResponse")]
        SOAPClient.SenecaES.EmployeeBase AddEmployee(SOAPClient.SenecaES.EmployeeAdd newItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AddEmployee", ReplyAction="http://tempuri.org/IEmployeeService/AddEmployeeResponse")]
        System.Threading.Tasks.Task<SOAPClient.SenecaES.EmployeeBase> AddEmployeeAsync(SOAPClient.SenecaES.EmployeeAdd newItem);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : SOAPClient.SenecaES.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<SOAPClient.SenecaES.IEmployeeService>, SOAPClient.SenecaES.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public SOAPClient.SenecaES.EmployeeBase[] AllEmployees() {
            return base.Channel.AllEmployees();
        }
        
        public System.Threading.Tasks.Task<SOAPClient.SenecaES.EmployeeBase[]> AllEmployeesAsync() {
            return base.Channel.AllEmployeesAsync();
        }
        
        public SOAPClient.SenecaES.EmployeeBase EmployeeById(System.Nullable<int> id) {
            return base.Channel.EmployeeById(id);
        }
        
        public System.Threading.Tasks.Task<SOAPClient.SenecaES.EmployeeBase> EmployeeByIdAsync(System.Nullable<int> id) {
            return base.Channel.EmployeeByIdAsync(id);
        }
        
        public SOAPClient.SenecaES.EmployeeBase AddEmployee(SOAPClient.SenecaES.EmployeeAdd newItem) {
            return base.Channel.AddEmployee(newItem);
        }
        
        public System.Threading.Tasks.Task<SOAPClient.SenecaES.EmployeeBase> AddEmployeeAsync(SOAPClient.SenecaES.EmployeeAdd newItem) {
            return base.Channel.AddEmployeeAsync(newItem);
        }
    }
}
